CREATE ROLE svc_application WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'R3FFxhfrSdGucCJ7';
	
GRANT SELECT ON ALL TABLES IN SCHEMA public TO svc_application;
GRANT SELECT ON ALL TABLES IN SCHEMA dbo TO svc_application;
GRANT insert ON ALL TABLES IN SCHEMA dbo TO svc_application;